//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NewsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.NewsResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Meta Element.
        /// </summary>
        internal static string AddMetaButton {
            get {
                return ResourceManager.GetString("AddMetaButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Meta Link.
        /// </summary>
        internal static string AddMetaLinkButton {
            get {
                return ResourceManager.GetString("AddMetaLinkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve the changes made to this article.
        /// </summary>
        internal static string ApproveContentToolTip {
            get {
                return ResourceManager.GetString("ApproveContentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        internal static string ArchiveDateGridHeader {
            get {
                return ResourceManager.GetString("ArchiveDateGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string AttributeContent {
            get {
                return ResourceManager.GetString("AttributeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string AttributeDefaultLanguage {
            get {
                return ResourceManager.GetString("AttributeDefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to delete the selected attribute..
        /// </summary>
        internal static string AttributeDeleteAlternateText {
            get {
                return ResourceManager.GetString("AttributeDeleteAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string AttributeDeleteButton {
            get {
                return ResourceManager.GetString("AttributeDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this attribute? It will be completely removed..
        /// </summary>
        internal static string AttributeDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("AttributeDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete (Selected).
        /// </summary>
        internal static string AttributeDeleteSelectedButton {
            get {
                return ResourceManager.GetString("AttributeDeleteSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected attribute down in list.
        /// </summary>
        internal static string AttributeDownAlternateText {
            get {
                return ResourceManager.GetString("AttributeDownAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string AttributeLanguageLabel {
            get {
                return ResourceManager.GetString("AttributeLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New attribute.
        /// </summary>
        internal static string AttributeNewLabel {
            get {
                return ResourceManager.GetString("AttributeNewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string AttributeRefreshAlternateText {
            get {
                return ResourceManager.GetString("AttributeRefreshAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string AttributeRefreshLink {
            get {
                return ResourceManager.GetString("AttributeRefreshLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string AttributeTitle {
            get {
                return ResourceManager.GetString("AttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string AttributeTitleRequired {
            get {
                return ResourceManager.GetString("AttributeTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected attribute up in list.
        /// </summary>
        internal static string AttributeUpAlternateText {
            get {
                return ResourceManager.GetString("AttributeUpAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string AttributeUpdateButton {
            get {
                return ResourceManager.GetString("AttributeUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Automatically select category].
        /// </summary>
        internal static string AutomaticallySelectCategory {
            get {
                return ResourceManager.GetString("AutomaticallySelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brief content.
        /// </summary>
        internal static string BriefContentLabel {
            get {
                return ResourceManager.GetString("BriefContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        internal static string ButtonDisabledPleaseWait {
            get {
                return ResourceManager.GetString("ButtonDisabledPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Content Changes (Delete Draft Version).
        /// </summary>
        internal static string CancelChangesToolTip {
            get {
                return ResourceManager.GetString("CancelChangesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel these changes?.
        /// </summary>
        internal static string CancelContentChangesButtonWarning {
            get {
                return ResourceManager.GetString("CancelContentChangesButtonWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must sign in to this site to post comments..
        /// </summary>
        internal static string CommentsRequireAuthenticationMessage {
            get {
                return ResourceManager.GetString("CommentsRequireAuthenticationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string CommentText {
            get {
                return ResourceManager.GetString("CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare To Current.
        /// </summary>
        internal static string CompareHistoryToCurrentLink {
            get {
                return ResourceManager.GetString("CompareHistoryToCurrentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This content has bee submitted for approval..
        /// </summary>
        internal static string ContentAwaitingApproval {
            get {
                return ResourceManager.GetString("ContentAwaitingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Content Changes Awaiting Approval.
        /// </summary>
        internal static string ContentAwaitingApprovalFormat {
            get {
                return ResourceManager.GetString("ContentAwaitingApprovalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This content has edits in progress..
        /// </summary>
        internal static string ContentEditsInProgress {
            get {
                return ResourceManager.GetString("ContentEditsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is required..
        /// </summary>
        internal static string ContentMetaContentRequired {
            get {
                return ResourceManager.GetString("ContentMetaContentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this meta element?.
        /// </summary>
        internal static string ContentMetaDeleteWarning {
            get {
                return ResourceManager.GetString("ContentMetaDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dir.
        /// </summary>
        internal static string ContentMetaDirLabel {
            get {
                return ResourceManager.GetString("ContentMetaDirLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ContentMetaGridCancelButton {
            get {
                return ResourceManager.GetString("ContentMetaGridCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ContentMetaGridDeleteButton {
            get {
                return ResourceManager.GetString("ContentMetaGridDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ContentMetaGridEditButton {
            get {
                return ResourceManager.GetString("ContentMetaGridEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string ContentMetaGridMoveDownButton {
            get {
                return ResourceManager.GetString("ContentMetaGridMoveDownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string ContentMetaGridMoveUpButton {
            get {
                return ResourceManager.GetString("ContentMetaGridMoveUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ContentMetaGridUpdateButton {
            get {
                return ResourceManager.GetString("ContentMetaGridUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lang.
        /// </summary>
        internal static string ContentMetaLangCodeLabel {
            get {
                return ResourceManager.GetString("ContentMetaLangCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this meta link?.
        /// </summary>
        internal static string ContentMetaLinkDeleteWarning {
            get {
                return ResourceManager.GetString("ContentMetaLinkDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Href is required..
        /// </summary>
        internal static string ContentMetaLinkHrefRequired {
            get {
                return ResourceManager.GetString("ContentMetaLinkHrefRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rel is required..
        /// </summary>
        internal static string ContentMetaLinkRelRequired {
            get {
                return ResourceManager.GetString("ContentMetaLinkRelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string ContentMetaMetaContentLabel {
            get {
                return ResourceManager.GetString("ContentMetaMetaContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Href.
        /// </summary>
        internal static string ContentMetaMetaHrefLabel {
            get {
                return ResourceManager.GetString("ContentMetaMetaHrefLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ContentMetaNameLabel {
            get {
                return ResourceManager.GetString("ContentMetaNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        internal static string ContentMetaNameRequired {
            get {
                return ResourceManager.GetString("ContentMetaNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rel.
        /// </summary>
        internal static string ContentMetaRelLabel {
            get {
                return ResourceManager.GetString("ContentMetaRelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme.
        /// </summary>
        internal static string ContentMetaSchemeLabel {
            get {
                return ResourceManager.GetString("ContentMetaSchemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HrefLang.
        /// </summary>
        internal static string ContentMetHrefLangLabel {
            get {
                return ResourceManager.GetString("ContentMetHrefLangLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string ContentTab {
            get {
                return ResourceManager.GetString("ContentTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content changes were rejected..
        /// </summary>
        internal static string ContentWasRejected {
            get {
                return ResourceManager.GetString("ContentWasRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy article.
        /// </summary>
        internal static string CopyNewsButton {
            get {
                return ResourceManager.GetString("CopyNewsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy images?.
        /// </summary>
        internal static string CopyNewsCopyImagesLabel {
            get {
                return ResourceManager.GetString("CopyNewsCopyImagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy article.
        /// </summary>
        internal static string CopyNewsLabel {
            get {
                return ResourceManager.GetString("CopyNewsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published?.
        /// </summary>
        internal static string CopyNewsPublishedLabel {
            get {
                return ResourceManager.GetString("CopyNewsPublishedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article has been copied successfully.
        /// </summary>
        internal static string CopyNewsSuccessMessage {
            get {
                return ResourceManager.GetString("CopyNewsSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New article title.
        /// </summary>
        internal static string CopyNewsTitleLabel {
            get {
                return ResourceManager.GetString("CopyNewsTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string CreatedByLabel {
            get {
                return ResourceManager.GetString("CreatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string CreatedDateGridHeader {
            get {
                return ResourceManager.GetString("CreatedDateGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on.
        /// </summary>
        internal static string CreatedOnLabel {
            get {
                return ResourceManager.GetString("CreatedOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version Created {0}.
        /// </summary>
        internal static string CurrentVersionHeadingFormat {
            get {
                return ResourceManager.GetString("CurrentVersionHeadingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy HH:mm.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All History.
        /// </summary>
        internal static string DeleteAllHistoryButton {
            get {
                return ResourceManager.GetString("DeleteAllHistoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all history for this content?.
        /// </summary>
        internal static string DeleteAllHistoryWarning {
            get {
                return ResourceManager.GetString("DeleteAllHistoryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteHistoryButton {
            get {
                return ResourceManager.GetString("DeleteHistoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this history item?.
        /// </summary>
        internal static string DeleteHistoryItemWarning {
            get {
                return ResourceManager.GetString("DeleteHistoryItemWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteImageAltText {
            get {
                return ResourceManager.GetString("DeleteImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string DialogCloseLink {
            get {
                return ResourceManager.GetString("DialogCloseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit This Content.
        /// </summary>
        internal static string EditImageAltText {
            get {
                return ResourceManager.GetString("EditImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert/Edit article.
        /// </summary>
        internal static string EditNewsPageTitle {
            get {
                return ResourceManager.GetString("EditNewsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert/Edit {0}.
        /// </summary>
        internal static string EditNewsPageTitleFormat {
            get {
                return ResourceManager.GetString("EditNewsPageTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        internal static string EmailSubjectEmailAddressRequired {
            get {
                return ResourceManager.GetString("EmailSubjectEmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string EmailSubjectLabel {
            get {
                return ResourceManager.GetString("EmailSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string EmailSubjectMessageLabel {
            get {
                return ResourceManager.GetString("EmailSubjectMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string EmailSubjectSendButton {
            get {
                return ResourceManager.GetString("EmailSubjectSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You! Your message has been sent..
        /// </summary>
        internal static string EmailSubjectThankYouLabel {
            get {
                return ResourceManager.GetString("EmailSubjectThankYouLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To email is required..
        /// </summary>
        internal static string EmailSubjectToEmailAddressRequired {
            get {
                return ResourceManager.GetString("EmailSubjectToEmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To email (*).
        /// </summary>
        internal static string EmailSubjectToEmailLabel {
            get {
                return ResourceManager.GetString("EmailSubjectToEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email address..
        /// </summary>
        internal static string EmailSubjectValidEmailAddressLabel {
            get {
                return ResourceManager.GetString("EmailSubjectValidEmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid To email address..
        /// </summary>
        internal static string EmailSubjectValidToEmailAddressLabel {
            get {
                return ResourceManager.GetString("EmailSubjectValidToEmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email (*).
        /// </summary>
        internal static string EmailSubjectYourEmailLabel {
            get {
                return ResourceManager.GetString("EmailSubjectYourEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        internal static string EmailSubjectYourNameLabel {
            get {
                return ResourceManager.GetString("EmailSubjectYourNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File attachment.
        /// </summary>
        internal static string FileAttachmentLabel {
            get {
                return ResourceManager.GetString("FileAttachmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string FileBrowserLink {
            get {
                return ResourceManager.GetString("FileBrowserLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url must start with ~/ or http:// or https:// and it should have no white spaces in it..
        /// </summary>
        internal static string FriendlyUrlRegexWarning {
            get {
                return ResourceManager.GetString("FriendlyUrlRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Lastest Article.
        /// </summary>
        internal static string GetLastestNews {
            get {
                return ResourceManager.GetString("GetLastestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide other contents on detail page.
        /// </summary>
        internal static string HideOtherContentsOnDetailPage {
            get {
                return ResourceManager.GetString("HideOtherContentsOnDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide pagination on detail page.
        /// </summary>
        internal static string HidePaginationOnDetailPage {
            get {
                return ResourceManager.GetString("HidePaginationOnDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected item(s)?.
        /// </summary>
        internal static string ImageDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ImageDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete (selected).
        /// </summary>
        internal static string ImageDeleteSelectedButton {
            get {
                return ResourceManager.GetString("ImageDeleteSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ImageFile {
            get {
                return ResourceManager.GetString("ImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string ImageInsertButton {
            get {
                return ResourceManager.GetString("ImageInsertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ImageTitle {
            get {
                return ResourceManager.GetString("ImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string ImageUpdateButton {
            get {
                return ResourceManager.GetString("ImageUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in feed.
        /// </summary>
        internal static string IncludeInFeedLabel {
            get {
                return ResourceManager.GetString("IncludeInFeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in search.
        /// </summary>
        internal static string IncludeInSearchLabel {
            get {
                return ResourceManager.GetString("IncludeInSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in sitemap.
        /// </summary>
        internal static string IncludeInSiteMapLabel {
            get {
                return ResourceManager.GetString("IncludeInSiteMapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string InsertAttribute {
            get {
                return ResourceManager.GetString("InsertAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Published?.
        /// </summary>
        internal static string IsPublishedLabel {
            get {
                return ResourceManager.GetString("IsPublishedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is sub category?.
        /// </summary>
        internal static string IsSubZoneSetting {
            get {
                return ResourceManager.GetString("IsSubZoneSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Per Page/Page Size.
        /// </summary>
        internal static string ItemsPerPageSetting {
            get {
                return ResourceManager.GetString("ItemsPerPageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Per Page/Page Size must be an integer. The default is 10.
        /// </summary>
        internal static string ItemsPerPageSettingRegexWarning {
            get {
                return ResourceManager.GetString("ItemsPerPageSettingRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string JobAddressLabel {
            get {
                return ResourceManager.GetString("JobAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required.
        /// </summary>
        internal static string JobAddressRequiredLabel {
            get {
                return ResourceManager.GetString("JobAddressRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for job.
        /// </summary>
        internal static string JobApplyLable {
            get {
                return ResourceManager.GetString("JobApplyLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string JobApplyRefreshLink {
            get {
                return ResourceManager.GetString("JobApplyRefreshLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You! Your message has been received..
        /// </summary>
        internal static string JobApplyThankYouLabel {
            get {
                return ResourceManager.GetString("JobApplyThankYouLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        internal static string JobApplyViewAllCVLabel {
            get {
                return ResourceManager.GetString("JobApplyViewAllCVLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach file 1.
        /// </summary>
        internal static string JobAttachFile1Label {
            get {
                return ResourceManager.GetString("JobAttachFile1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach file 2.
        /// </summary>
        internal static string JobAttachFile2Label {
            get {
                return ResourceManager.GetString("JobAttachFile2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach File.
        /// </summary>
        internal static string JobAttachFileLabel {
            get {
                return ResourceManager.GetString("JobAttachFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Info.
        /// </summary>
        internal static string JobCandidateInfoLabel {
            get {
                return ResourceManager.GetString("JobCandidateInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string JobEmailLabel {
            get {
                return ResourceManager.GetString("JobEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        internal static string JobEmailRequiredLabel {
            get {
                return ResourceManager.GetString("JobEmailRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is required.
        /// </summary>
        internal static string JobEmptyMessageWarning {
            get {
                return ResourceManager.GetString("JobEmptyMessageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string JobFullNameLabel {
            get {
                return ResourceManager.GetString("JobFullNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is required.
        /// </summary>
        internal static string JobFullNameRequiredLabel {
            get {
                return ResourceManager.GetString("JobFullNameRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string JobMessageLabel {
            get {
                return ResourceManager.GetString("JobMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the information below.
        /// </summary>
        internal static string JobNoteLabel {
            get {
                return ResourceManager.GetString("JobNoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string JobPhoneLabel {
            get {
                return ResourceManager.GetString("JobPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is required.
        /// </summary>
        internal static string JobPhoneRequiredLabel {
            get {
                return ResourceManager.GetString("JobPhoneRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string JobPositionLabel {
            get {
                return ResourceManager.GetString("JobPositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is required.
        /// </summary>
        internal static string JobPositionRequiredLabel {
            get {
                return ResourceManager.GetString("JobPositionRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required.
        /// </summary>
        internal static string JobRequiredLabel {
            get {
                return ResourceManager.GetString("JobRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string JobRequiredStarLabel {
            get {
                return ResourceManager.GetString("JobRequiredStarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid.
        /// </summary>
        internal static string JobValidEmailLabel {
            get {
                return ResourceManager.GetString("JobValidEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List CV ({0}).
        /// </summary>
        internal static string JobViewCVFormat {
            get {
                return ResourceManager.GetString("JobViewCVFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List CV.
        /// </summary>
        internal static string JobViewCVTitle {
            get {
                return ResourceManager.GetString("JobViewCVTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load first item?.
        /// </summary>
        internal static string LoadFirstItemSetting {
            get {
                return ResourceManager.GetString("LoadFirstItemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Items To Get.
        /// </summary>
        internal static string MaxItemsToGet {
            get {
                return ResourceManager.GetString("MaxItemsToGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be an integer. The default is 5.
        /// </summary>
        internal static string MaxItemsToGetRegexWarning {
            get {
                return ResourceManager.GetString("MaxItemsToGetRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Meta Tags.
        /// </summary>
        internal static string MetaAdditionalLabel {
            get {
                return ResourceManager.GetString("MetaAdditionalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Description.
        /// </summary>
        internal static string MetaDescriptionLabel {
            get {
                return ResourceManager.GetString("MetaDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Keywords.
        /// </summary>
        internal static string MetaKeywordsLabel {
            get {
                return ResourceManager.GetString("MetaKeywordsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Data.
        /// </summary>
        internal static string MetaTab {
            get {
                return ResourceManager.GetString("MetaTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Comment.
        /// </summary>
        internal static string NewComment {
            get {
                return ResourceManager.GetString("NewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Enter a Valid Begin Date.
        /// </summary>
        internal static string NewsBeginDateRequiredHelp {
            get {
                return ResourceManager.GetString("NewsBeginDateRequiredHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string NewsCommentCommentLabel {
            get {
                return ResourceManager.GetString("NewsCommentCommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string NewsCommentCountLabel {
            get {
                return ResourceManager.GetString("NewsCommentCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string NewsCommentPostCommentButton {
            get {
                return ResourceManager.GetString("NewsCommentPostCommentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string NewsCommentPostCommentButtonAccessKey {
            get {
                return ResourceManager.GetString("NewsCommentPostCommentButtonAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me?.
        /// </summary>
        internal static string NewsCommentRemeberMeLabel {
            get {
                return ResourceManager.GetString("NewsCommentRemeberMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments are closed on this content..
        /// </summary>
        internal static string NewsCommentsClosedMessage {
            get {
                return ResourceManager.GetString("NewsCommentsClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allowed.
        /// </summary>
        internal static string NewsCommentsNotAllowed {
            get {
                return ResourceManager.GetString("NewsCommentsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve This To Prove You are a Real Person, not a SPAM script..
        /// </summary>
        internal static string NewsCommentSolveQuestionMessage {
            get {
                return ResourceManager.GetString("NewsCommentSolveQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        internal static string NewsCommentsUnlimited {
            get {
                return ResourceManager.GetString("NewsCommentsUnlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string NewsCommentTitleLabel {
            get {
                return ResourceManager.GetString("NewsCommentTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string NewsCommentUrlLabel {
            get {
                return ResourceManager.GetString("NewsCommentUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NewsCommentUserNameLabel {
            get {
                return ResourceManager.GetString("NewsCommentUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy.
        /// </summary>
        internal static string NewsDateFormat {
            get {
                return ResourceManager.GetString("NewsDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this comment?.
        /// </summary>
        internal static string NewsDeleteCommentWarning {
            get {
                return ResourceManager.GetString("NewsDeleteCommentWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected item(s)?.
        /// </summary>
        internal static string NewsDeleteMultiWarning {
            get {
                return ResourceManager.GetString("NewsDeleteMultiWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        internal static string NewsDeleteWarning {
            get {
                return ResourceManager.GetString("NewsDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a future start date or un-check &quot;Is Published&quot; to create an unpublished draft..
        /// </summary>
        internal static string NewsDraftInstructions {
            get {
                return ResourceManager.GetString("NewsDraftInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Comments for.
        /// </summary>
        internal static string NewsEditAllowedCommentsForDaysPrefix {
            get {
                return ResourceManager.GetString("NewsEditAllowedCommentsForDaysPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string NewsEditCancelButton {
            get {
                return ResourceManager.GetString("NewsEditCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string NewsEditCancelButtonAccessKey {
            get {
                return ResourceManager.GetString("NewsEditCancelButtonAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string NewsEditCommentsDaysLabel {
            get {
                return ResourceManager.GetString("NewsEditCommentsDaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string NewsEditDeleteButton {
            get {
                return ResourceManager.GetString("NewsEditDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string NewsEditDeleteButtonAccessKey {
            get {
                return ResourceManager.GetString("NewsEditDeleteButtonAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string NewsEditDescriptionLabel {
            get {
                return ResourceManager.GetString("NewsEditDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        internal static string NewsEditDisplayOrderLabel {
            get {
                return ResourceManager.GetString("NewsEditDisplayOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert/Edit article.
        /// </summary>
        internal static string NewsEditHeading {
            get {
                return ResourceManager.GetString("NewsEditHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string NewsEditImageTitleLabel {
            get {
                return ResourceManager.GetString("NewsEditImageTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string NewsEditItemUrlLabel {
            get {
                return ResourceManager.GetString("NewsEditItemUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string NewsEditLanguageLabel {
            get {
                return ResourceManager.GetString("NewsEditLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not care.
        /// </summary>
        internal static string NewsEditLanguageNotCareLabel {
            get {
                return ResourceManager.GetString("NewsEditLanguageNotCareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string NewsEditLink {
            get {
                return ResourceManager.GetString("NewsEditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string NewsEditPreviewLabel {
            get {
                return ResourceManager.GetString("NewsEditPreviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Continue.
        /// </summary>
        internal static string NewsEditSaveAndContinue {
            get {
                return ResourceManager.GetString("NewsEditSaveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; New.
        /// </summary>
        internal static string NewsEditSaveAndNew {
            get {
                return ResourceManager.GetString("NewsEditSaveAndNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string NewsEditStartDateLabel {
            get {
                return ResourceManager.GetString("NewsEditStartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string NewsEditTitleLabel {
            get {
                return ResourceManager.GetString("NewsEditTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string NewsEditUpdateButton {
            get {
                return ResourceManager.GetString("NewsEditUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string NewsEditUpdateButtonAccessKey {
            get {
                return ResourceManager.GetString("NewsEditUpdateButtonAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewed.
        /// </summary>
        internal static string NewsEditViewedLabel {
            get {
                return ResourceManager.GetString("NewsEditViewedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email subject.
        /// </summary>
        internal static string NewsEmailLink {
            get {
                return ResourceManager.GetString("NewsEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Version History?.
        /// </summary>
        internal static string NewsEnableVersioningSetting {
            get {
                return ResourceManager.GetString("NewsEnableVersioningSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        internal static string NewsFeatureName {
            get {
                return ResourceManager.GetString("NewsFeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string NewsFeedbackLabel {
            get {
                return ResourceManager.GetString("NewsFeedbackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new {0}.
        /// </summary>
        internal static string NewsInsertFormat {
            get {
                return ResourceManager.GetString("NewsInsertFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string NewsInsertLabel {
            get {
                return ResourceManager.GetString("NewsInsertLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new article.
        /// </summary>
        internal static string NewsInsertLink {
            get {
                return ResourceManager.GetString("NewsInsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article list.
        /// </summary>
        internal static string NewsList {
            get {
                return ResourceManager.GetString("NewsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string NewsListAllFilter {
            get {
                return ResourceManager.GetString("NewsListAllFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My articles.
        /// </summary>
        internal static string NewsListByUser {
            get {
                return ResourceManager.GetString("NewsListByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete (selected).
        /// </summary>
        internal static string NewsListDeleteSelectedButton {
            get {
                return ResourceManager.GetString("NewsListDeleteSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string NewsListFilterStatusLabel {
            get {
                return ResourceManager.GetString("NewsListFilterStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title contain.
        /// </summary>
        internal static string NewsListFilterTitleLabel {
            get {
                return ResourceManager.GetString("NewsListFilterTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} List.
        /// </summary>
        internal static string NewsListFormat {
            get {
                return ResourceManager.GetString("NewsListFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string NewsListSearchButton {
            get {
                return ResourceManager.GetString("NewsListSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string NewsListStatusFilterAll {
            get {
                return ResourceManager.GetString("NewsListStatusFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string NewsListUpdateButton {
            get {
                return ResourceManager.GetString("NewsListUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string NewsManageCreatedBy {
            get {
                return ResourceManager.GetString("NewsManageCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Date.
        /// </summary>
        internal static string NewsManagePublishedDate {
            get {
                return ResourceManager.GetString("NewsManagePublishedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        internal static string NewsMoreLinkText {
            get {
                return ResourceManager.GetString("NewsMoreLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected article to the right zone.
        /// </summary>
        internal static string NewsMoveLeftAlternateText {
            get {
                return ResourceManager.GetString("NewsMoveLeftAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move article.
        /// </summary>
        internal static string NewsMoveLink {
            get {
                return ResourceManager.GetString("NewsMoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected article to the right zone.
        /// </summary>
        internal static string NewsMoveRightAlternateText {
            get {
                return ResourceManager.GetString("NewsMoveRightAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move article.
        /// </summary>
        internal static string NewsMoveTilte {
            get {
                return ResourceManager.GetString("NewsMoveTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0}.
        /// </summary>
        internal static string NewsMoveTilteFormat {
            get {
                return ResourceManager.GetString("NewsMoveTilteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;&gt;.
        /// </summary>
        internal static string NewsNextLink {
            get {
                return ResourceManager.GetString("NewsNextLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article permissions.
        /// </summary>
        internal static string NewsPermissions {
            get {
                return ResourceManager.GetString("NewsPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special position.
        /// </summary>
        internal static string NewsPositionLabel {
            get {
                return ResourceManager.GetString("NewsPositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special article.
        /// </summary>
        internal static string NewsPositionLink {
            get {
                return ResourceManager.GetString("NewsPositionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special position.
        /// </summary>
        internal static string NewsPositionSetting {
            get {
                return ResourceManager.GetString("NewsPositionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Previous.
        /// </summary>
        internal static string NewsPreviousLink {
            get {
                return ResourceManager.GetString("NewsPreviousLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string NewsPrintLink {
            get {
                return ResourceManager.GetString("NewsPrintLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string NewsSearchButton {
            get {
                return ResourceManager.GetString("NewsSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        internal static string NewsSearchName {
            get {
                return ResourceManager.GetString("NewsSearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected list.
        /// </summary>
        internal static string NewsSelectedListLabel {
            get {
                return ResourceManager.GetString("NewsSelectedListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose {0}.
        /// </summary>
        internal static string NewsSelectFormat {
            get {
                return ResourceManager.GetString("NewsSelectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose article.
        /// </summary>
        internal static string NewsSelectLabel {
            get {
                return ResourceManager.GetString("NewsSelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on.
        /// </summary>
        internal static string NewsSortByCreatedOn {
            get {
                return ResourceManager.GetString("NewsSortByCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string NewsSortByDefault {
            get {
                return ResourceManager.GetString("NewsSortByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most viewed.
        /// </summary>
        internal static string NewsSortByMostViewed {
            get {
                return ResourceManager.GetString("NewsSortByMostViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string NewsSortByRandom {
            get {
                return ResourceManager.GetString("NewsSortByRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string NewsSortBySetting {
            get {
                return ResourceManager.GetString("NewsSortBySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article special.
        /// </summary>
        internal static string NewsSpecialFeatureName {
            get {
                return ResourceManager.GetString("NewsSpecialFeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special article.
        /// </summary>
        internal static string NewsSpecialLink {
            get {
                return ResourceManager.GetString("NewsSpecialLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special article.
        /// </summary>
        internal static string NewsSpecialTilte {
            get {
                return ResourceManager.GetString("NewsSpecialTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special {0}.
        /// </summary>
        internal static string NewsSpecialTilteFormat {
            get {
                return ResourceManager.GetString("NewsSpecialTilteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special article.
        /// </summary>
        internal static string NewsSpecialTitle {
            get {
                return ResourceManager.GetString("NewsSpecialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string NewsTagAddNewButton {
            get {
                return ResourceManager.GetString("NewsTagAddNewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagged news.
        /// </summary>
        internal static string NewsTaggedNews {
            get {
                return ResourceManager.GetString("NewsTaggedNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string NewsTagKeywordLabel {
            get {
                return ResourceManager.GetString("NewsTagKeywordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name.
        /// </summary>
        internal static string NewsTagName {
            get {
                return ResourceManager.GetString("NewsTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk edit.
        /// </summary>
        internal static string NewsTagsBulkEdit {
            get {
                return ResourceManager.GetString("NewsTagsBulkEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected tag(s)?.
        /// </summary>
        internal static string NewsTagsDeleteMultiWarning {
            get {
                return ResourceManager.GetString("NewsTagsDeleteMultiWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News tags.
        /// </summary>
        internal static string NewsTagsLabel {
            get {
                return ResourceManager.GetString("NewsTagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News tags.
        /// </summary>
        internal static string NewsTagsLink {
            get {
                return ResourceManager.GetString("NewsTagsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News tags.
        /// </summary>
        internal static string NewsTagsTitle {
            get {
                return ResourceManager.GetString("NewsTagsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string NewsTemplate {
            get {
                return ResourceManager.GetString("NewsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail height.
        /// </summary>
        internal static string NewsThumbnailHeightSetting {
            get {
                return ResourceManager.GetString("NewsThumbnailHeightSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail width.
        /// </summary>
        internal static string NewsThumbnailWidthSetting {
            get {
                return ResourceManager.GetString("NewsThumbnailWidthSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        internal static string NewsTimeFormat {
            get {
                return ResourceManager.GetString("NewsTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article type.
        /// </summary>
        internal static string NewsTypeLabel {
            get {
                return ResourceManager.GetString("NewsTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article type.
        /// </summary>
        internal static string NewsTypeSetting {
            get {
                return ResourceManager.GetString("NewsTypeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a different Url. The entered Url conflicts with an existing page..
        /// </summary>
        internal static string NewsUrlConflictWithPhysicalPageError {
            get {
                return ResourceManager.GetString("NewsUrlConflictWithPhysicalPageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Url is already in use. You cannot use the same Url for different pages, unless you use the full Url with http. However, doing this will result in multiple menu pointing to the same actual category..
        /// </summary>
        internal static string NewsUrlInUseErrorMessage {
            get {
                return ResourceManager.GetString("NewsUrlInUseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new window.
        /// </summary>
        internal static string OpenInNewWindowLabel {
            get {
                return ResourceManager.GetString("OpenInNewWindowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other news.
        /// </summary>
        internal static string OtherNewsLabel {
            get {
                return ResourceManager.GetString("OtherNewsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Products.
        /// </summary>
        internal static string OtherProductLabel {
            get {
                return ResourceManager.GetString("OtherProductLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Projects.
        /// </summary>
        internal static string OtherProjectLabel {
            get {
                return ResourceManager.GetString("OtherProjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Url is already in use. You cannot use the same Url for different pages..
        /// </summary>
        internal static string PageUrlInUseNewsErrorMessage {
            get {
                return ResourceManager.GetString("PageUrlInUseNewsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent category.
        /// </summary>
        internal static string ParentZoneSetting {
            get {
                return ResourceManager.GetString("ParentZoneSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent categories.
        /// </summary>
        internal static string ParentZonesSetting {
            get {
                return ResourceManager.GetString("ParentZonesSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse the begin date..
        /// </summary>
        internal static string ParseDateFailureMessage {
            get {
                return ResourceManager.GetString("ParseDateFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create article.
        /// </summary>
        internal static string PermissionsNewsCreate {
            get {
                return ResourceManager.GetString("PermissionsNewsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete article.
        /// </summary>
        internal static string PermissionsNewsDelete {
            get {
                return ResourceManager.GetString("PermissionsNewsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update article.
        /// </summary>
        internal static string PermissionsNewsUpdate {
            get {
                return ResourceManager.GetString("PermissionsNewsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View article list.
        /// </summary>
        internal static string PermissionsNewsViewList {
            get {
                return ResourceManager.GetString("PermissionsNewsViewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent action by.
        /// </summary>
        internal static string RecentActionByLabel {
            get {
                return ResourceManager.GetString("RecentActionByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent action on.
        /// </summary>
        internal static string RecentActionOnLabel {
            get {
                return ResourceManager.GetString("RecentActionOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Content.
        /// </summary>
        internal static string RejectContentHeading {
            get {
                return ResourceManager.GetString("RejectContentHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject the changes made to this article.
        /// </summary>
        internal static string RejectContentToolTip {
            get {
                return ResourceManager.GetString("RejectContentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &lt;b&gt;{0}&lt;/b&gt; to reject the content changes made to &lt;b&gt;{1}&lt;/b&gt;. You can enter reasons for your rejection below, these may help the original content author &lt;b&gt;{2}&lt;/b&gt; in correcting the content..
        /// </summary>
        internal static string RejectionIntroduction {
            get {
                return ResourceManager.GetString("RejectionIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Changes.
        /// </summary>
        internal static string RejectionPageUpdateButton {
            get {
                return ResourceManager.GetString("RejectionPageUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Items To Show.
        /// </summary>
        internal static string RelatedItemsToShow {
            get {
                return ResourceManager.GetString("RelatedItemsToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Items To Show must be an integer. The default is 5.
        /// </summary>
        internal static string RelatedItemsToShowRegexWarning {
            get {
                return ResourceManager.GetString("RelatedItemsToShowRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Approval for this Draft Content Instance.
        /// </summary>
        internal static string RequestApprovalToolTip {
            get {
                return ResourceManager.GetString("RequestApprovalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore To Editor.
        /// </summary>
        internal static string RestoreToEditorButton {
            get {
                return ResourceManager.GetString("RestoreToEditorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string RowNumber {
            get {
                return ResourceManager.GetString("RowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Preview.
        /// </summary>
        internal static string SaveAndPreviewButton {
            get {
                return ResourceManager.GetString("SaveAndPreviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchPageTitle {
            get {
                return ResourceManager.GetString("SearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About &lt;strong&gt;{0}&lt;/strong&gt; results for keyword &lt;strong&gt;{1}&lt;/strong&gt; &lt;span class=&apos;searchduration&apos;&gt;({2} seconds)&lt;/span&gt;.
        /// </summary>
        internal static string SearchResultsFormat {
            get {
                return ResourceManager.GetString("SearchResultsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we could not find search results that match your keywords.
        /// </summary>
        internal static string SearchResultsNotFound {
            get {
                return ResourceManager.GetString("SearchResultsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a category.
        /// </summary>
        internal static string SelectZoneMessage {
            get {
                return ResourceManager.GetString("SelectZoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all images on news list.
        /// </summary>
        internal static string ShowAllImagesInNewsList {
            get {
                return ResourceManager.GetString("ShowAllImagesInNewsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Articles From Child Categories.
        /// </summary>
        internal static string ShowAllNewsFromChildZoneSetting {
            get {
                return ResourceManager.GetString("ShowAllNewsFromChildZoneSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show attribute in news listing.
        /// </summary>
        internal static string ShowAttributesInNewsList {
            get {
                return ResourceManager.GetString("ShowAttributesInNewsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hidden contents on detail page.
        /// </summary>
        internal static string ShowHiddenContentsOnDetailPage {
            get {
                return ResourceManager.GetString("ShowHiddenContentsOnDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show option.
        /// </summary>
        internal static string ShowOptionLabel {
            get {
                return ResourceManager.GetString("ShowOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Page Left Content in Article?.
        /// </summary>
        internal static string ShowPageLeftContentSetting {
            get {
                return ResourceManager.GetString("ShowPageLeftContentSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Page Right Content in Article?.
        /// </summary>
        internal static string ShowPageRightContentSetting {
            get {
                return ResourceManager.GetString("ShowPageRightContentSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        internal static string ThumbnailLabel {
            get {
                return ResourceManager.GetString("ThumbnailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string TitleRequiredWarning {
            get {
                return ResourceManager.GetString("TitleRequiredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version as of {0}.
        /// </summary>
        internal static string VersionAsOfHeadingFormat {
            get {
                return ResourceManager.GetString("VersionAsOfHeadingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version History.
        /// </summary>
        internal static string VersionHistory {
            get {
                return ResourceManager.GetString("VersionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be an url starting with http:// or https://.
        /// </summary>
        internal static string WebSiteUrlRegexWarning {
            get {
                return ResourceManager.GetString("WebSiteUrlRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This content was approved by an editor..
        /// </summary>
        internal static string WorkflowApproved {
            get {
                return ResourceManager.GetString("WorkflowApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This content has been submitted for approval. If it is approved it will become live content..
        /// </summary>
        internal static string WorkflowAwaitingApproval {
            get {
                return ResourceManager.GetString("WorkflowAwaitingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This content was cancelled by author..
        /// </summary>
        internal static string WorkflowCancelled {
            get {
                return ResourceManager.GetString("WorkflowCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Content Changes Awaiting Approval.
        /// </summary>
        internal static string WorkflowContentAwaitingApprovalFormat {
            get {
                return ResourceManager.GetString("WorkflowContentAwaitingApprovalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Content Changes Rejected.
        /// </summary>
        internal static string WorkflowContentRejectedFormat {
            get {
                return ResourceManager.GetString("WorkflowContentRejectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This content has edits in progress but has not yet been submitted for approval..
        /// </summary>
        internal static string WorkflowDraft {
            get {
                return ResourceManager.GetString("WorkflowDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Draft.
        /// </summary>
        internal static string WorkflowDraftFormat {
            get {
                return ResourceManager.GetString("WorkflowDraftFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This content was rejected by an editor. Please use the content editor to see the rejection notes..
        /// </summary>
        internal static string WorkflowRejected {
            get {
                return ResourceManager.GetString("WorkflowRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Draft.
        /// </summary>
        internal static string WorkflowSaveDraftButton {
            get {
                return ResourceManager.GetString("WorkflowSaveDraftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string WorkflowStateLable {
            get {
                return ResourceManager.GetString("WorkflowStateLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Status.
        /// </summary>
        internal static string WorkflowStatus {
            get {
                return ResourceManager.GetString("WorkflowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string XsltFileName {
            get {
                return ResourceManager.GetString("XsltFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail page template.
        /// </summary>
        internal static string XsltFileNameDetailPage {
            get {
                return ResourceManager.GetString("XsltFileNameDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping article.
        /// </summary>
        internal static string ZoneNewsFeatureName {
            get {
                return ResourceManager.GetString("ZoneNewsFeatureName", resourceCulture);
            }
        }
    }
}
